### ISSUE TITLE
If the default context is activated, changes are not logged and assigned to it

### ISSUE THREAD

**Issue by tthuem** [tthuem/VariantSync#4]

**Comment by 1Tristan** [comment]
ongoing implementation: Now, changes are logged and assigned to the default context. 
TODO: They still need to be shown in one of the synchronization views.

**Comment by 1Tristan** [comment]
Default context is tagged and tagged code is highlighted in the editor (bright grey - color can be changed using the CustomColorDialog). Changes of the default context are not listed in one of the synchronization views.
