### ISSUE TITLE
broken build

### ISSUE THREAD

**Issue by jeremiaheinle** [tthuem/VariantSync#67]
FeatureContext ComboBox does not display anymore, because of error in build.

Stacktrace is a follows:
Caused by: java.lang.RuntimeException: Failed to invoke public org.prop4j.Node() with no args
at com.google.gson.Gson.fromJson(Gson.java:932)

**Comment by wurstbroteater** [comment]
I could not reproduce your error but interpreting the error log leads to the following conclusion: In some cases GSON has a problem with the propj4.Node serialisiation. To avoid this, the `Node featureMapping` in the AST.java should be delcared as `transient`. 
fixed #67
